version: '3.8'

services:
  # Base de données MySQL
  db:
    image: mysql:8.0
    container_name: contesdefees_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network
    ports:
      - "3306:3306"

  # WordPress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: contesdefees_wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: 'true'
    volumes:
      - wordpress_data:/var/www/html
      - ./fairy-tale-generator:/var/www/html/wp-content/plugins/fairy-tale-generator
      - ./themes:/var/www/html/wp-content/themes/custom
      - ./uploads:/var/www/html/wp-content/uploads
    networks:
      - wordpress_network

  # PHPMyAdmin pour gérer la base de données
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    container_name: contesdefees_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - wordpress_network

volumes:
  db_data:
  wordpress_data:

networks:
  wordpress_network:
    driver: bridge
